version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build -t antiumsoft/php-hosting-deployer:$TAG -t antiumsoft/php-hosting-deployer:latest .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push antiumsoft/php-hosting-deployer:$TAG
          docker push antiumsoft/php-hosting-deployer:latest
